[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.12.0"
nom = "7.1.3"
indoc = "2.0.1"
rustc-hash = "1.1.0"
num = "0.4.1"
ring-algorithm = "0.7.0"
# slab = "0.4.8"
# rayon = "1.7.0"
# regex = "1.8.1"
# lazy_static = "1.4.0"
